# Generated by Django 5.2.5 on 2025-08-16 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductivityInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('productivity_tip', 'Productivity Tip'), ('pattern_analysis', 'Pattern Analysis'), ('time_optimization', 'Time Optimization'), ('stress_reduction', 'Stress Reduction'), ('habit_suggestion', 'Habit Suggestion'), ('achievement_opportunity', 'Achievement Opportunity')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('confidence_score', models.FloatField(help_text='AI confidence in this insight (0-1)')),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('action_taken', models.BooleanField(default=False)),
                ('action_description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('daily', 'Daily Goal'), ('weekly', 'Weekly Goal'), ('monthly', 'Monthly Goal'), ('habit_21day', '21-Day Habit'), ('custom', 'Custom Goal')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_value', models.IntegerField(help_text='Target number to achieve')),
                ('current_progress', models.IntegerField(default=0)),
                ('progress_unit', models.CharField(default='tasks', help_text='Unit of measurement', max_length=50)),
                ('start_date', models.DateField()),
                ('target_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('failed', 'Failed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Share goal with other users')),
                ('reward_xp', models.IntegerField(default=100, help_text='XP reward for completion')),
                ('custom_reward', models.CharField(blank=True, help_text='Personal reward description', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField(default=0, help_text='Total experience points earned')),
                ('current_level', models.IntegerField(default=1, help_text='Current user level')),
                ('xp_to_next_level', models.IntegerField(default=100, help_text='XP needed for next level')),
                ('total_tasks_created', models.IntegerField(default=0)),
                ('total_tasks_completed', models.IntegerField(default=0)),
                ('total_tasks_overdue', models.IntegerField(default=0)),
                ('current_daily_streak', models.IntegerField(default=0, help_text='Current consecutive days with completed tasks')),
                ('longest_daily_streak', models.IntegerField(default=0, help_text='Longest streak ever achieved')),
                ('current_weekly_streak', models.IntegerField(default=0, help_text='Current consecutive weeks with goals met')),
                ('longest_weekly_streak', models.IntegerField(default=0)),
                ('total_time_saved', models.IntegerField(default=0, help_text='Total minutes saved through task completion')),
                ('average_completion_time', models.FloatField(default=0.0, help_text='Average task completion time in hours')),
                ('productivity_score', models.FloatField(default=0.0, help_text='Overall productivity score (0-100)')),
                ('completion_rate', models.FloatField(default=0.0, help_text='Task completion percentage')),
                ('punctuality_score', models.FloatField(default=100.0, help_text='On-time completion percentage')),
                ('stress_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('work_life_balance_score', models.FloatField(default=75.0, help_text='Work-life balance score (0-100)')),
                ('burnout_risk', models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='low', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Statistics',
                'verbose_name_plural': 'User Statistics',
            },
        ),
        migrations.CreateModel(
            name='XPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('related_task_id', models.IntegerField(blank=True, null=True)),
                ('related_event_id', models.IntegerField(blank=True, null=True)),
                ('related_goal_id', models.IntegerField(blank=True, null=True)),
                ('user_statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_logs', to='stats.userstatistics')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tasks_created', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('tasks_overdue', models.IntegerField(default=0)),
                ('events_attended', models.IntegerField(default=0)),
                ('total_work_time', models.IntegerField(default=0, help_text='Total minutes worked')),
                ('focus_time', models.IntegerField(default=0, help_text='Deep focus time in minutes')),
                ('break_time', models.IntegerField(default=0, help_text='Break time in minutes')),
                ('daily_productivity_score', models.FloatField(default=0.0)),
                ('mood_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5, help_text='Daily mood rating (1-10)')),
                ('energy_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5, help_text='Energy level (1-10)')),
                ('daily_goal_set', models.BooleanField(default=False)),
                ('daily_goal_achieved', models.BooleanField(default=False)),
                ('daily_goal_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Statistics',
                'verbose_name_plural': 'Daily Statistics',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StreakTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_type', models.CharField(choices=[('daily_tasks', 'Daily Task Completion'), ('weekly_goals', 'Weekly Goal Achievement'), ('monthly_targets', 'Monthly Target Achievement'), ('perfect_days', 'Perfect Days'), ('early_completions', 'Early Task Completions'), ('habit_21day', '21-Day Habit Challenge'), ('custom', 'Custom Streak')], max_length=50)),
                ('current_count', models.IntegerField(default=0)),
                ('best_count', models.IntegerField(default=0)),
                ('last_updated', models.DateField()),
                ('streak_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('target_count', models.IntegerField(blank=True, help_text='Target streak length', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('milestone_rewards', models.JSONField(default=dict, help_text='Milestone rewards configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-current_count'],
                'unique_together': {('user', 'streak_type', 'streak_name')},
            },
        ),
        migrations.CreateModel(
            name='AchievementBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('first_task', 'First Task'), ('first_week', 'First Week'), ('perfect_day', 'Perfect Day'), ('perfect_week', 'Perfect Week'), ('perfect_month', 'Perfect Month'), ('early_bird', 'Early Bird'), ('night_owl', 'Night Owl'), ('streak_master', 'Streak Master'), ('productivity_guru', 'Productivity Guru'), ('level', 'Level Achievement'), ('time_saver', 'Time Saver'), ('event_master', 'Event Master'), ('consistency_king', 'Consistency King'), ('overachiever', 'Overachiever'), ('wellness_warrior', 'Wellness Warrior'), ('habit_builder', 'Habit Builder'), ('goal_getter', 'Goal Getter'), ('custom', 'Custom Achievement')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-trophy', help_text='FontAwesome icon class', max_length=50)),
                ('color', models.CharField(default='gold', help_text='Badge color', max_length=20)),
                ('unlocked_at', models.DateTimeField()),
                ('is_rare', models.BooleanField(default=False, help_text='Rare achievements are harder to obtain')),
                ('rarity_level', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('user_statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='stats.userstatistics')),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user_statistics', 'badge_type', 'title')},
            },
        ),
    ]
