# Generated by Django 5.2.5 on 2025-08-14 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='A brief description of the task.', max_length=255, verbose_name='description')),
                ('scheduled_time', models.DateTimeField(help_text='The date and time when the task is scheduled.', verbose_name='scheduled time')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the task was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the task was last updated.', verbose_name='updated at')),
                ('completed', models.BooleanField(default=False, help_text='Indicates whether the task has been completed.', verbose_name='completed')),
                ('completed_at', models.DateTimeField(blank=True, help_text='The date and time when the task was completed.', null=True, verbose_name='completed at')),
                ('event', models.ForeignKey(blank=True, help_text='The event this task is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='events.event')),
                ('owner', models.ForeignKey(help_text='The user who owns this task.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['scheduled_time'],
            },
        ),
    ]
